### ISSUE TITLE
Create forest tree mushroom model

### ISSUE THREAD

**Issue by tlegorju** [Krayt78/Scott-s-Escape#26]
The tree is now more of a mushroom type of thing

### **First variant**
- [x] Model first variant
- [x] LOD first variant
- [x] Texture first variant

### **Second variant**
- [x] Model second variant
- [x] LOD second variant
- [ ] Texture second variant

### **Third variant**
- [x] Model third variant
- [x] LOD third variant
- [ ] Texture third variant

### **Fourth variant**
- [x] Model fourth variant
- [x] LOD fourth variant
- [ ] Texture fourth variant

### **Fifth variant**
- [x] Model fifth variant
- [x] LOD fifth variant
- [ ] Texture fifth variant

### **Sixth variant**
- [x] Model sixth variant
- [x] LOD sixth variant
- [ ] Texture sixth variant

**Comment by TKiraa** [comment]
![fdbe6d69242ca437fce005cf5e0d6ee7](https://user-images.githubusercontent.com/9019094/78339557-f1c43a00-7594-11ea-9bae-67b300c3b483.png)
![66adf71874f60bf8f3765f8020ebc697](https://user-images.githubusercontent.com/9019094/78339560-f25cd080-7594-11ea-8849-2e35b4cbe62f.png)
