### ISSUE TITLE
Create rock models

### ISSUE THREAD

**Issue by tlegorju** [Krayt78/Scott-s-Escape#27]
Création de plusieurs version de rocher

**Comment by TKiraa** [comment]
Rock 01 version 1:
- [x] model
- [x] UV
- [x] texture
- [x] LOD

![bd0f9a39c86c73f0f55e36c79437c3c3](https://user-images.githubusercontent.com/9019094/84492645-c5205300-aca6-11ea-87a4-096d4ad34c9f.png)

Rock 02 version 1:
- [x] model
- [x] UV
- [x] texture
- [x] LOD

![5ab7844810252ecbba9b0fcfd00f72d3](https://user-images.githubusercontent.com/9019094/84492714-e5501200-aca6-11ea-9e70-554f01bbc79e.png)

**Comment by TKiraa** [comment]
Ajout de 15 rochers de plus, je ferme l'issue
