### ISSUE TITLE
Create mushroom models

### ISSUE THREAD

**Issue by tlegorju** [Krayt78/Scott-s-Escape#29]
**- Mushroom variant 1 :**

- [x] Model mushroom variant 1
- [x] UV mushroom variant 1
- [x] LOD mushroom variant 1
- [x] Texture mushroom variant 1

**- Mushroom variant 2 :**
- [x] Model mushroom variant 2
- [x] UV mushroom variant 2
- [x] LOD mushroom variant 2
- [x] Texture mushroom variant 2

**- Mushroom variant 3 :**
- [x] Model mushroom variant 3
- [x] UV mushroom variant 3
- [x] LOD mushroom variant 3
- [x] Texture mushroom variant 3

**- Mushroom variant 4 :**
- [x] Model mushroom variant 4
- [x] UV mushroom variant 4
- [x] LOD mushroom variant 4
- [x] Texture mushroom variant 4

**Comment by TKiraa** [comment]
![edeb781a6e501aba70679f837f593b16](https://user-images.githubusercontent.com/9019094/78338673-7ada7180-7593-11ea-85fc-e4e9a0e4abff.png)

UV and LOD done for each mushroom

**Comment by TKiraa** [comment]
5 rework des muchrooms, je ferme car cela suffit
