### ISSUE TITLE
Create the armor of the guard

### ISSUE THREAD

**Issue by NolanGougeon** [Krayt78/Scott-s-Escape#36]
### **Armor of the guard**

- [x] Model Armor
- [x] UV Armor
- [x] Texture Armor

**Comment by TKiraa** [comment]
![edeb781a6e501aba70679f837f593b16](https://user-images.githubusercontent.com/9019094/78338673-7ada7180-7593-11ea-85fc-e4e9a0e4abff.png)

UV and LOD done for each mushroom

**Comment by TKiraa** [comment]
![b6c3a03845be665ba184becfa6f1de50](https://user-images.githubusercontent.com/9019094/78339341-9d20bf00-7594-11ea-84d1-9942e803ee4b.png)

**Comment by TKiraa** [comment]
Armure terminé, je ferme.
