### ISSUE TITLE
Create mother tree mushroom model

### ISSUE THREAD

**Issue by tlegorju** [Krayt78/Scott-s-Escape#50]
- [x] model
- [x] UV
- [ ] texture
- [x] LOD

**Comment by TKiraa** [comment]
![eaca3eb9133f47016e5d0ee0195b6482](https://user-images.githubusercontent.com/9019094/78338055-58942400-7592-11ea-980b-045fc9c00f39.png)

**Comment by TKiraa** [comment]
idée abandonnée donc je ferme
